### ISSUE TITLE
problem with cell_height

### ISSUE THREAD

**Issue by kozilla** [troolee/gridstack.js#83]
Hi,

Thx for a nice plugin. I am playing around with your tool and found some issue with cell_height function. I am creating new widget by :
$('.grid-stack').gridstack({
            width: 3,
            height:3,
	    cell_height : 100
});	

grid.add_widget(el, 1, 1, 1, 1, true);

all works nice , but then when  try do resize height of element to 50px  :

grid.cell_height(50); 

it crashes with "TypeError: this._styles.rules is undefined" in _ update_styles function.

Could you provide any example how  height can be modified after initialization , its necessary for me as I have to  keep  correct size ratio when I resize window (as for now only width is responsive).

Thanks,

**Comment by troolee** [comment]
I will check this.

**Comment by troolee** [comment]
It is fixed now.

**Comment by kozilla** [comment]
Hi Pavel,

Thanks for looking at my issue. I have retested your fix and I am afraid that it still doesn't work correctly :(

it works fine under Chrome and IE, how ever FireFox (36.0.1) still throws error :

TypeError: this._styles.rules is undefined         gridstack.js:487:19

which refers to :
...
  while (this._styles.rules.length) { 
...

Any thoughts on that ?

Thanks,
Karol

**Comment by troolee** [comment]
Please re-open the issue and add this comment on github.

I will check it.


//wbr Pavel Reznikov <pashka.reznikov@gmail.com>

**Comment by kozilla** [comment]
I have created new issue instead ;)

Thanks for so quick response :D
