### ISSUE TITLE
 cell_height(val) doesnt work in FireFox.

### ISSUE THREAD

**Issue by kozilla** [troolee/gridstack.js#90]
Hi Pavel,

Thanks for looking on issue with setting cell_height. I have retested your fix and I am afraid that it still doesn't work correctly :(

it works fine under Chrome and IE, how ever FireFox (lates version 36.0.1) still throws error :

TypeError: this._styles.rules is undefined gridstack.js:487:19

which refers to :
...
while (this._styles.rules.length) {
...

when cell_height(val) is called.

Any thoughts on that ?

Thanks,
Karol

**Comment by troolee** [comment]
It is fixed now

**Comment by m4hm0od** [comment]
Hi troolee,

I use latest version of gridstack.js but still have this issue. what should i do?
